### ISSUE TITLE
Request: Styling for definition lists

### ISSUE THREAD

**Issue by ColtonProvias** [vjeantet/hugo-theme-docdock#132]
The much forgotten, yet still useful definition list is supported fully by blackfriday. Yet this theme handles this wondrous list type in the dullest manner of all: not at all.

```md
For an example of a Definition List in blackfriday-compatible markdown:

Definition List
: A very, very important list type in HTML, perhaps more so than ul and ol.

Ordered/Unordered Lists
: Inferior lists.

Hero
: A programmer who rights the wrong of the poor styling of definition lists.
```

A temporary fix, of course, is to add something like this to a stylesheet included in the theme:

```css
dt {
	font-weight: bold;
}

dd {
	margin-left: 2em;
	margin-bottom: 0.5em;
}
```
